name: publish

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"   # e.g. v1.2.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tooling
        run: |
          python -m pip install -U pip
          pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Verify metadata
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true 
